apiVersion: v1
kind: Service
metadata:
  name: mirai-backend
  namespace: mirai
  labels:
    app: mirai-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: mirai-backend
